### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by mpuckett159**
Adds golangci linting on pull request and DockerHub build process on release.

### CODE REVIEW

**Comment by barrytam20** [comment]
would we need to change the compose file so that it uses the latest images on dockerhub instead of building a new image?

**Comment by mpuckett159** [comment]
So I was thinking about that and not 100% sure how to handle it exactly. I think it might be best to rename the current docker-compose file to `spd-lookup-build-docker-compose.yml` and just have a normal `docker-compose.yml` file so that the default is to pull from DockerHub, but we can specify the build file with the `-f` option if we need to, say if DockerHub is down or we have changes in the repo that we don't want to necessarily build into the image or something, I dunno. Basically just a dual option and maintain the other docker-compose file outside of the CI/CD pipeline.

**Comment by AetherUnbound** [comment]
Great call @barrytam20! I'm with you @mpuckett159, I think we can have one for CI/CD/local dev and another for general use/deployment which is just `docker-compose.yml`. I don't have any particular preferences on the name of the other file :slightly_smiling_face:

**Comment by mpuckett159** [comment]
Do we think we should include the CI/CD docker-compose.yml in this repo or maintain that locally? This is pretty new to me so I'm not sure how exactly to handle this situation.

**Comment by AetherUnbound** [comment]
Definitely okay to have two docker compose files in this repo, most people will default to the `docker-compose.yml` because they'll just run `docker-compose` with default settings, so that's the one we should have pulling from Dockerhub. The other can be `docker-compose-local.yml`, that's a pretty common pattern I'd say!

**Comment by mpuckett159** [comment]
Ok I think that sounds good then, I'll make the change after this meeting I'm in and push the change.

**Comment by mpuckett159** [comment]
Alright I pushed some images I built locally to DockerHub to test and make sure this all worked out and as one would expect it took a lot less time to pull from there than build locally haha.

**Review by barrytam20 — APPROVED** [review]

**Review by AetherUnbound — APPROVED** [review]
:rocket:

**Pull request merged**
